PRAGMA foreign_keys = ON;

INSERT OR IGNORE INTO districts (id, name_fa, name_en, slug) VALUES
  (1, 'منطقه ۱', 'District 1', 'district-1'),
  (2, 'منطقه ۲', 'District 2', 'district-2'),
  (3, 'منطقه ۳', 'District 3', 'district-3'),
  (4, 'منطقه ۴', 'District 4', 'district-4'),
  (5, 'منطقه ۵', 'District 5', 'district-5'),
  (6, 'منطقه ۶', 'District 6', 'district-6'),
  (7, 'منطقه ۷', 'District 7', 'district-7'),
  (8, 'منطقه ۸', 'District 8', 'district-8'),
  (9, 'منطقه ۹', 'District 9', 'district-9'),
  (10, 'منطقه ۱۰', 'District 10', 'district-10'),
  (11, 'منطقه ۱۱', 'District 11', 'district-11'),
  (12, 'منطقه ۱۲', 'District 12', 'district-12'),
  (13, 'منطقه ۱۳', 'District 13', 'district-13'),
  (14, 'منطقه ۱۴', 'District 14', 'district-14'),
  (15, 'منطقه ۱۵', 'District 15', 'district-15'),
  (16, 'منطقه ۱۶', 'District 16', 'district-16'),
  (17, 'منطقه ۱۷', 'District 17', 'district-17'),
  (18, 'منطقه ۱۸', 'District 18', 'district-18'),
  (19, 'منطقه ۱۹', 'District 19', 'district-19'),
  (20, 'منطقه ۲۰', 'District 20', 'district-20'),
  (21, 'منطقه ۲۱', 'District 21', 'district-21'),
  (22, 'منطقه ۲۲', 'District 22', 'district-22');

-- Slugs below are PLACEHOLDERS. Run /api/discover-slugs to get real ones.
INSERT OR IGNORE INTO neighborhoods (district_id, name_fa, slug) VALUES
  (1, 'تجریش', 'tehran-tajrish'), (1, 'زعفرانیه', 'tehran-zaferanieh'), (1, 'شمیران', 'tehran-shemiran'), (1, 'الهیه', 'tehran-elahiyeh'), (1, 'نیاوران', 'tehran-niavaran'),
  (2, 'شهرک غرب', 'tehran-shahrak-gharb'), (2, 'سعادت‌آباد', 'tehran-saadatabad'), (2, 'پونک', 'tehran-punak'), (2, 'شهرآرا', 'tehran-shahrara'), (2, 'گیشا', 'tehran-gisha'),
  (3, 'ونک', 'tehran-vanak'), (3, 'یوسف‌آباد', 'tehran-yusefabad'), (3, 'امیرآباد', 'tehran-amirabad'), (3, 'جردن', 'tehran-jordan'), (3, 'اختیاریه', 'tehran-ekhtiyariyeh'),
  (4, 'تهرانپارس', 'tehran-tehranpars-4'), (4, 'رسالت', 'tehran-resalat'), (4, 'هروی', 'tehran-heravi'), (4, 'پاسداران', 'tehran-pasdaran'), (4, 'قنات‌کوثر', 'tehran-ghanat-kosar'),
  (5, 'شهران', 'tehran-shahran'), (5, 'پونک', 'tehran-punak-5'), (5, 'جنت‌آباد', 'tehran-jannatabad'), (5, 'کن', 'tehran-kan'), (5, 'باغ‌فیض', 'tehran-baghfeiz'),
  (6, 'فاطمی', 'tehran-fatemi'), (6, 'گاندی', 'tehran-gandi'), (6, 'ونک', 'tehran-vanak-6'), (6, 'کشاورز', 'tehran-keshavarz'), (6, 'امیرآباد', 'tehran-amirabad-6'),
  (7, 'سبلان', 'tehran-sabalan'), (7, 'بهشتی', 'tehran-beheshti'), (7, 'مطهری', 'tehran-motahari'), (7, 'کریم‌خان', 'tehran-karimkhan'), (7, 'عباس‌آباد', 'tehran-abbasabad'),
  (8, 'سیدخندان', 'tehran-seyedkhandan'), (8, 'لشکر', 'tehran-lashkar'), (8, 'تسلیحات', 'tehran-taslihat'), (8, 'نارمک', 'tehran-narmak-8'), (8, 'هفت‌حوض', 'tehran-hafthoz-8'),
  (9, 'مهرآباد', 'tehran-mehrabad'), (9, 'آذری', 'tehran-azari'), (9, 'جی', 'tehran-ji'), (9, 'استادمعین', 'tehran-ostad-moein'), (9, 'دستغیب', 'tehran-dastgheib'),
  (10, 'آزادی', 'tehran-azadi'), (10, 'کارون', 'tehran-karun'), (10, 'هفت‌چنار', 'tehran-haftchenar'), (10, 'سلسبیل', 'tehran-salsabil'), (10, 'بریانک', 'tehran-briyanak'),
  (11, 'حسن‌آباد', 'tehran-hasanabad'), (11, 'انقلاب', 'tehran-enghelab'), (11, 'جمهوری', 'tehran-jomhouri'), (11, 'منیریه', 'tehran-moniriyeh'), (11, 'راه‌آهن', 'tehran-railway'),
  (12, 'بهار', 'tehran-bahar'), (12, 'فردوسی', 'tehran-ferdowsi'), (12, 'لاله‌زار', 'tehran-lalehzar'), (12, 'بازار', 'tehran-bazaar'), (12, 'پامنار', 'tehran-pamenar'),
  (13, 'نارمک', 'tehran-narmak-13'), (13, 'تهرانپارس', 'tehran-tehranpars-13'), (13, 'هفت‌حوض', 'tehran-hafthoz'), (13, 'پیروزی', 'tehran-pirouzi-13'), (13, 'نیروی هوایی', 'tehran-niroo-havaei'),
  (14, 'شکوفه', 'tehran-shekoofeh'), (14, 'ابوذر', 'tehran-abusar'), (14, 'قیام', 'tehran-ghiam'), (14, 'نبرد', 'tehran-nabard'), (14, 'دولاب', 'tehran-doolab'),
  (15, 'مشیریه', 'tehran-moshirieh'), (15, 'افسریه', 'tehran-afsarieh'), (15, 'جوادیه', 'tehran-javadieh'), (15, 'کیانشهر', 'tehran-kianshahr'), (15, 'مسعودیه', 'tehran-masoudieh'),
  (16, 'نازی‌آباد', 'tehran-naziabad'), (16, 'یاخچی‌آباد', 'tehran-yakhchiabad'), (16, 'خزانه', 'tehran-khazaneh'), (16, 'جوادیه', 'tehran-javadieh-16'), (16, 'باغ‌آذری', 'tehran-baghazari'),
  (17, 'زمزم', 'tehran-zamzam'), (17, 'آذربایجان', 'tehran-azerbaijan'), (17, 'امامزاده', 'tehran-emamzadeh'), (17, 'ابوذر', 'tehran-abusar-17'), (17, 'فلاح', 'tehran-fallah'),
  (18, 'یافت‌آباد', 'tehran-yaftabad'), (18, 'ولیعصر', 'tehran-valiasr-18'), (18, 'شادآباد', 'tehran-shadabad'), (18, 'خلیج فارس', 'tehran-khalij-fars'), (18, 'فردوس', 'tehran-ferdous-18'),
  (19, 'خانی‌آباد', 'tehran-khaniabad'), (19, 'اسماعیل‌آباد', 'tehran-ismailabad'), (19, 'نعمت‌آباد', 'tehran-nematabad'), (19, 'رسالت', 'tehran-resalat-19'), (19, 'عبدل‌آباد', 'tehran-abdolabad'),
  (20, 'شهرری', 'tehran-shahrrey'), (20, 'دولت‌آباد', 'tehran-dolatabad'), (20, 'صفائیه', 'tehran-safaeieh'), (20, 'جوانمرد قصاب', 'tehran-javanmard-ghassab'), (20, 'کهریزک', 'tehran-kahrizak-20'),
  (21, 'وردآورد', 'tehran-vardavard'), (21, 'ایران‌خودرو', 'tehran-irankhodro'), (21, 'تهرانسر', 'tehran-tehransar'), (21, 'چیتگر جنوبی', 'tehran-chitgar-jonoubi'), (21, 'شهرک آزادی', 'tehran-shahrak-azadi'),
  (22, 'چیتگر', 'tehran-chitgar'), (22, 'پیکان‌شهر', 'tehran-peykanshahr'), (22, 'دهکده المپیک', 'tehran-olympic'), (22, 'دریاچه چیتگر', 'tehran-chitgar-lake'), (22, 'زیبادشت', 'tehran-zibadasht');